# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            iluvbiking
tagline:          'a bikeshare site'
description:      'a site with all of the best resources for bikeshare programs'
url:              https://iluvbiking.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/iluvbiking

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iluvbiking/iluvbiking

gems: [jekyll-paginate, jekyll-gist]